# Generated by Django 3.1.1 on 2021-03-22 19:11

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20210322_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
