# Generated by Django 3.1.1 on 2021-03-23 23:51

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20210323_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=django_cryptography.fields.encrypt(models.TextField(max_length=500)),
        ),
    ]
